import { LoaderCircle } from 'lucide-react'
import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useCloneApi } from '../../api/api-context'
import type { VoiceClone } from '../../api/clone-api'
import { Button } from '../../components/ui/button'
import { SampleInput } from './sample-input'

export function CloneEnrolForm({ onCreated }: { onCreated(clone: VoiceClone): void }) {
  const api = useCloneApi()
  const { t } = useTranslation(); const [name, setName] = useState(''); const [sample, setSample] = useState(''); const [consent, setConsent] = useState(false); const [processing, setProcessing] = useState(false); const [error, setError] = useState('')
  const ready = name.trim().length >= 2 && Boolean(sample) && consent
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!ready) { setError(t('clone.invalid')); return }; setProcessing(true); setError(''); try { const clone = await api.createClone(name.trim(), sample); onCreated(clone); setName(''); setSample(''); setConsent(false) } catch { setError(t('clone.failed')) } finally { setProcessing(false) } }
  return <form onSubmit={event => void submit(event)} className="rounded-[var(--radius-panel)] border border-[var(--color-border)] bg-[var(--color-surface)] p-4 sm:p-6"><div><p className="text-xs font-bold tracking-[0.08em] text-[var(--color-primary)]">{t('clone.demo')}</p><h2 className="mt-1 text-xl font-bold">{t('clone.enrolTitle')}</h2></div><div className="mt-5 grid gap-5"><label className="grid gap-1.5 text-sm font-semibold">{t('clone.nameLabel')}<input required minLength={2} value={name} onChange={event => setName(event.target.value)} className="min-h-11 rounded-[var(--radius-control)] border border-[var(--color-border)] bg-[var(--color-bg)] px-3 text-base font-normal focus-visible:border-[var(--color-primary)] focus-visible:outline-2 focus-visible:outline-[var(--focus-ring)] focus-visible:outline-offset-2 focus-visible:outline-solid md:text-sm" placeholder={t('clone.namePlaceholder')} /></label><SampleInput onChange={setSample} /><label className="flex cursor-pointer gap-3 rounded-[var(--radius-control)] border border-[var(--color-border)] bg-[var(--color-surface-soft)] p-3.5 text-sm leading-6 transition-colors hover:border-[var(--color-muted)]"><input required checked={consent} onChange={event => setConsent(event.target.checked)} className="mt-1 size-5 shrink-0 accent-[var(--color-primary)] focus-visible:outline-2 focus-visible:outline-[var(--focus-ring)]" type="checkbox" /><span><strong className="text-[var(--color-text)]">{t('clone.consentTitle')}</strong><br /><span className="text-[var(--color-muted)]">{t('clone.consentText')}</span></span></label>{error && <p role="alert" className="text-sm text-[var(--color-danger)]">{error}</p>}<Button type="submit" disabled={!ready || processing}>{processing && <LoaderCircle className="mr-2 animate-spin" size={17} />}{processing ? t('clone.processing') : t('clone.create')}</Button></div></form>
}
